name: CI_Tests

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:

    backend-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: backend
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Node.js setup
              uses: actions/setup-node@v1
              with:
                    node-version: ${{ matrix.node-version }}
            
            - name: install dependencies
              run: npm install

            - run: npm test

    frontend-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: frontend
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Node.js setup
              uses: actions/setup-node@v1
              with:
                    node-version: ${{ matrix.node-version }}
            
            - name: install dependencies
              run: npm install
